name: Auto-add PRs and Commits to GitHub Project

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to GitHub Project
        uses: mheap/add-to-project@v1
        with:
          project-url: https://github.com/users/MarkOtwane/projects/6
        env:
          GH_TOKEN: ${{ secrets.MY_PROJECT_TOKEN }}
