name: Auto-add PRs and Issues to GitHub Project V2

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to GitHub Project V2
        uses: mheap/github-project-action@v2
        with:
          project-url: https://github.com/users/MarkOtwane/projects/6
        env:
          GH_TOKEN: ${{ secrets.MY_PROJECT_TOKEN }}
