name: Auto-add PRs to GitHub Project

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository-projects: write
    steps:
      - name: Add Pull Request to GitHub Project
        uses: actions/add-to-project@v0.6.0
        with:
          project-url: https://github.com/users/MarkOtwane/projects/6
          github-token: ${{ secrets.MY_PROJECT_TOKEN }}
