name: Auto-add PRs and Commits to GitHub Project

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository-projects: write
    steps:
      - name: Add to GitHub Project
        uses: actions/add-to-project@v1.0.1  # Use a specific version for stability
        with:
          project-url: https://github.com/users/MarkOtwane/projects/6
          github-token: ${{ secrets.MY_PROJECT_TOKEN }}
