name: Auto-add PRs and Issues to GitHub Project V2

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      repository-projects: write  # ✅ needed for Projects V2

    steps:
      - name: Add issue or PR to GitHub Project V2
        uses: actions/add-to-project@v1.0.1  # ✅ Official, correct repo and version
        with:
          project-url: https://github.com/users/MarkOtwane/projects/6
          github-token: ${{ secrets.MY_PROJECT_TOKEN }}  # ✅ Must be a PAT with required scopes
